// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class apiUsersCredit
    {
        public int pkApiUserCreditId { get; set; }
        public int? fkApiuserId { get; set; }
        public string apiUserName { get; set; }
        public DateTime? createdate { get; set; }
        public int? SMSLimit { get; set; }
        public int? SMSConsumed { get; set; }
        public int? status { get; set; }
        public int? thresholdPercentage { get; set; }
        public DateTime? lastNotificationDate { get; set; }
        public bool? notificationSent { get; set; }
        public string Type { get; set; }
        public string Application { get; set; }

        public virtual apiUser fkApiuser { get; set; }
    }
}