// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class apiUser
    {
        public apiUser()
        {
            apiUsersCredits = new HashSet<apiUsersCredit>();
        }

        public int pkApiUserId { get; set; }
        public string api { get; set; }
        public string apiUserName { get; set; }
        public DateTime? createdate { get; set; }
        public DateTime? modifydate { get; set; }
        public int? status { get; set; }

        public virtual ICollection<apiUsersCredit> apiUsersCredits { get; set; }
    }
}