// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class EditEmployeeDetail
    {
        public long EdtEmpDetID { get; set; }
        public string TableName { get; set; }
        public string EmployeeCode { get; set; }
        public string UserName { get; set; }
        public string Gender { get; set; }
        public string Designation { get; set; }
        public string PositionGrade { get; set; }
        public string Department { get; set; }
        public string SubDepartment { get; set; }
        public DateTime? DOB { get; set; }
        public DateTime? DateOfAnniversary { get; set; }
        public DateTime? DateOfJoining { get; set; }
        public string Location { get; set; }
        public string SubArea { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string PersonalEmailId { get; set; }
        public string Toemploy { get; set; }
        public string AboutUs { get; set; }
        public string Photo { get; set; }
        public int? status { get; set; }
        public string ReportingOfficer { get; set; }
        public string remarks { get; set; }
        public string ExtensionNo { get; set; }
    }
}