// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class EmailSmsManagement
    {
        public int Id { get; set; }
        public string ClientId { get; set; }
        public string AppId { get; set; }
        public string TemplateId { get; set; }
        public string Phone_Email { get; set; }
        public string ListOfVariable { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ServiceType { get; set; }
    }
}