// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class EmployeeDependentDocument
    {
        public int DocumentId { get; set; }
        public long fkDependentId { get; set; }
        public string DocumentName { get; set; }
        public string DocumentType { get; set; }
        public string FilePath { get; set; }
        public DateTime UploadedDate { get; set; }
        public string UploadedBy { get; set; }
        public int? Status { get; set; }
        public string Remarks { get; set; }

        public virtual MstEmployeeDependent fkDependent { get; set; }
    }
}