// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class kraformRejectedLog
    {
        public int pkkraformRejectedLog { get; set; }
        public int pkkraForm { get; set; }
        public int? fkUserId { get; set; }
        public string KeyResultArea { get; set; }
        public string Priority { get; set; }
        public decimal? Weightage { get; set; }
        public DateTime? TargetDate { get; set; }
        public int? status { get; set; }
        public DateTime? CreatedDate { get; set; }
        public Guid? groupId { get; set; }
        public string RejectedRemarks { get; set; }
        public string forwhat { get; set; }
        public string Remarks { get; set; }
        public string reportingOfficer { get; set; }
        public string DueTo { get; set; }

        public virtual kraUser fkUser { get; set; }
    }
}