// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class kraUser
    {
        public int pkKraUser { get; set; }
        public long? fkAutoId { get; set; }
        public string Session { get; set; }
        public int? status { get; set; }
        public string userPost { get; set; }
        public string userDept { get; set; }
        public string pop { get; set; }
        public string reportingAutoId { get; set; }
        public string reportingPost { get; set; }
        public string reportingDept { get; set; }
        public string reportingpop { get; set; }
        public string remarks { get; set; }
        public int? ReviseState { get; set; }
        public DateTime? createdDate { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public DateTime? modifiedDate { get; set; }

        public virtual MstEmployeeMaster fkAuto { get; set; }
    }
}