// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MasterHolidayCalendar
    {
        public int HolidayId { get; set; }
        public int SerialNumber { get; set; }
        public DateTime HolidayDate { get; set; }
        public string HolidayDescription { get; set; }
        public string HolidayType { get; set; }
        public string DayOfWeek { get; set; }
        public int UnitId { get; set; }
        public string UnitName { get; set; }
        public bool? IsActive { get; set; }
        public string CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}