// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstContractMaster
    {
        public MstContractMaster()
        {
            MstContractEmployeeMasters = new HashSet<MstContractEmployeeMaster>();
            RegisterContractEmployeeParentOrganzationNavigations = new HashSet<RegisterContractEmployee>();
            RegisterContractEmployeefkContracts = new HashSet<RegisterContractEmployee>();
        }

        public int PkContractid { get; set; }
        public string Contractor { get; set; }
        public string ContractDate { get; set; }
        public bool? status { get; set; }
        public string DeptDfccil { get; set; }

        public virtual ICollection<MstContractEmployeeMaster> MstContractEmployeeMasters { get; set; }
        public virtual ICollection<RegisterContractEmployee> RegisterContractEmployeeParentOrganzationNavigations { get; set; }
        public virtual ICollection<RegisterContractEmployee> RegisterContractEmployeefkContracts { get; set; }
    }
}