// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstContractEmployeeMaster
    {
        public int PkCntEmpMstId { get; set; }
        public int? fkContractid { get; set; }
        public long? fkEmployeeMasterAutoId { get; set; }
        public int? status { get; set; }
        public string Remarks { get; set; }
        public string OfficeOrder { get; set; }

        public virtual MstContractMaster fkContract { get; set; }
        public virtual MstEmployeeMaster fkEmployeeMasterAuto { get; set; }
    }
}