// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstDepartment
    {
        public int Departmentid { get; set; }
        public string Department { get; set; }
        public int? UnitId { get; set; }
        public int? Status { get; set; }
        public string IP { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
    }
}