// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstEmployeeMasterProfileImage
    {
        public int Id { get; set; }
        public string EmployeeCode { get; set; }
        public int Status { get; set; }
        public string ImageType { get; set; }
        public string Image { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}