// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstEmployeeMaster
    {
        public MstEmployeeMaster()
        {
            MstContractEmployeeMasters = new HashSet<MstContractEmployeeMaster>();
            MstEmployeeDependents = new HashSet<MstEmployeeDependent>();
            kraUsers = new HashSet<kraUser>();
            tblEmployeeOfTheMonths = new HashSet<tblEmployeeOfTheMonth>();
            todoLists = new HashSet<todoList>();
        }

        public long EmployeeMasterAutoId { get; set; }
        public string EmployeeCode { get; set; }
        public string Gender { get; set; }
        public string UserName { get; set; }
        public string Post { get; set; }
        public string GenericDesignation { get; set; }
        public decimal? Positions { get; set; }
        public string PositionGrade { get; set; }
        public string DeptDFCCIL { get; set; }
        public string SubDeptDF { get; set; }
        public DateTime? DOB { get; set; }
        public DateTime? DORetirement { get; set; }
        public string Location { get; set; }
        public DateTime? DORecruiting { get; set; }
        public DateTime? DOJDFCCIL { get; set; }
        public string DOTEnds { get; set; }
        public DateTime? DepTenurecompletiondate { get; set; }
        public DateTime? DepExtensionuptodate { get; set; }
        public decimal? DeputationTenure { get; set; }
        public string DORepatriation { get; set; }
        public DateTime? DOAbsorption { get; set; }
        public DateTime? DOfirstPromotion { get; set; }
        public DateTime? DOsecondPromotion { get; set; }
        public string DOthirdPromotion { get; set; }
        public string DOReemployment { get; set; }
        public string DOAbsconding { get; set; }
        public string TOemploy { get; set; }
        public string EmpSubgroup { get; set; }
        public string EthnicOrigin { get; set; }
        public string Religion { get; set; }
        public string RBFileNo { get; set; }
        public string LastDesignation { get; set; }
        public string Services { get; set; }
        public string DITSDOARailway { get; set; }
        public string ParentRailway { get; set; }
        public string GazettedNonGazetted { get; set; }
        public string DOletter { get; set; }
        public string PersonnelArea { get; set; }
        public string PersonnelSubArea { get; set; }
        public string Mobile { get; set; }
        public string Pwd { get; set; }
        public string emailAddress { get; set; }
        public int? Status { get; set; }
        public string Modify_By { get; set; }
        public DateTime? Modify_Date { get; set; }
        public string Modify_IP { get; set; }
        public int? UserType { get; set; }
        public string designation { get; set; }
        public string AboutUs { get; set; }
        public string ExtnNo { get; set; }
        public string FaxNo { get; set; }
        public string MTNNo { get; set; }
        public string Photo { get; set; }
        public DateTime? AnniversaryDate { get; set; }
        public string PersonalMobile { get; set; }
        public string PersonalEmailAddress { get; set; }
        public string ParentOrganzation { get; set; }
        public double? duration { get; set; }
        public string ReportingOfficer { get; set; }
        public string PAN { get; set; }

        public virtual ICollection<MstContractEmployeeMaster> MstContractEmployeeMasters { get; set; }
        public virtual ICollection<MstEmployeeDependent> MstEmployeeDependents { get; set; }
        public virtual ICollection<kraUser> kraUsers { get; set; }
        public virtual ICollection<tblEmployeeOfTheMonth> tblEmployeeOfTheMonths { get; set; }
        public virtual ICollection<todoList> todoLists { get; set; }
    }
}