// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstEmployeeDependent
    {
        public MstEmployeeDependent()
        {
            EmployeeDependentDocuments = new HashSet<EmployeeDependentDocument>();
        }

        public long pkDependentId { get; set; }
        public long? fkEmployeeMasterAutoId { get; set; }
        public string DName { get; set; }
        public string Relation { get; set; }
        public int Age { get; set; }
        public int? status { get; set; }
        public string Gender { get; set; }
        public string remarks { get; set; }
        public DateTime? createdDate { get; set; }
        public string createdBy { get; set; }
        public DateTime? updatedDate { get; set; }
        public string updatedBy { get; set; }

        public virtual MstEmployeeMaster fkEmployeeMasterAuto { get; set; }
        public virtual ICollection<EmployeeDependentDocument> EmployeeDependentDocuments { get; set; }
    }
}