// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstPost
    {
        public int Postid { get; set; }
        public string Post { get; set; }
        public int? Status { get; set; }
        public string Description { get; set; }
    }
}