// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class mstPositionGreade
    {
        public string PositionGrade { get; set; }
        public double? PGOrder { get; set; }
        public int pkPGId { get; set; }
    }
}