// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class MstUnit
    {
        public int Unitid { get; set; }
        public string UnitName { get; set; }
        public int? SectionId { get; set; }
        public int? Status { get; set; }
        public string IP { get; set; }
        public DateTime? CreateDate { get; set; }
        public string CreateBy { get; set; }
        public int? SequenceID { get; set; }
        public string Abbrivation { get; set; }
    }
}