// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class RegisterContractEmployee
    {
        public long ContEmpID { get; set; }
        public string UserName { get; set; }
        public string Gender { get; set; }
        public string DeptDFCCIL { get; set; }
        public DateTime? DOB { get; set; }
        public DateTime? DOJDFCCIL { get; set; }
        public string Location { get; set; }
        public string Mobile { get; set; }
        public string emailAddress { get; set; }
        public string TOemploy { get; set; }
        public int? Status { get; set; }
        public string remarks { get; set; }
        public string AppointmentDoc { get; set; }
        public int? fkContractid { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public int? ParentOrganzation { get; set; }
        public string ProfilePhoto { get; set; }

        public virtual MstContractMaster ParentOrganzationNavigation { get; set; }
        public virtual MstContractMaster fkContract { get; set; }
    }
}