// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class SMSLogDetail
    {
        public int SMSSentId { get; set; }
        public string MobileNumber { get; set; }
        public string SMSText { get; set; }
        public DateTime? SentOn { get; set; }
        public string ResponseText { get; set; }
        public string UserId { get; set; }
        public int? Status { get; set; }
        public string IPAddress { get; set; }
        public bool? ArchiveStatus { get; set; }
    }
}