// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class tblDeviceOTP
    {
        public long pkDeviceOTPid { get; set; }
        public string UserId { get; set; }
        public string DeviceId { get; set; }
        public string Otp { get; set; }
        public DateTime? CreateDate { get; set; }
        public DateTime? Expiration { get; set; }
        public int? status { get; set; }
    }
}