// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class tblDownLoadLog
    {
        public int pkDownLoadLogId { get; set; }
        public long? fkEmployeeMasterAutoId { get; set; }
        public int? fkPolItemId { get; set; }
        public DateTime? createDate { get; set; }

        public virtual MstEmployeeMaster fkEmployeeMasterAuto { get; set; }
        public virtual tblPolicyItem fkPolItem { get; set; }
    }
}