// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class tblEmployeeOfTheMonth
    {
        public int pkId { get; set; }
        public long? fkEmployeeMasterAutoId { get; set; }
        public int? mnth { get; set; }
        public int? yr { get; set; }
        public DateTime? createDate { get; set; }
        public string createBy { get; set; }
        public int? status { get; set; }
        public string photo { get; set; }

        public virtual MstEmployeeMaster fkEmployeeMasterAuto { get; set; }
    }
}