// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class tblNoticeBoard
    {
        public int pkNoticeId { get; set; }
        public string msg { get; set; }
        public string doc { get; set; }
        public int? status { get; set; }
        public string createBy { get; set; }
        public DateTime? createDate { get; set; }
        public string subject { get; set; }
        public string description { get; set; }
    }
}