// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class tblPolice
    {
        public tblPolice()
        {
            tblPolicyItems = new HashSet<tblPolicyItem>();
        }

        public int pkPolId { get; set; }
        public string PolicyHead { get; set; }
        public int? ParentPolicyId { get; set; }
        public int? status { get; set; }
        public DateTime? createdate { get; set; }
        public DateTime? modifydate { get; set; }
        public string createBy { get; set; }
        public string modifyBy { get; set; }

        public virtual ICollection<tblPolicyItem> tblPolicyItems { get; set; }
    }
}