// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class tblPolicyItem
    {
        public tblPolicyItem()
        {
            tblDownLoadLogs = new HashSet<tblDownLoadLog>();
        }

        public int pkPolItemId { get; set; }
        public int? fkPolId { get; set; }
        public string itemSubject { get; set; }
        public string itemType { get; set; }
        public string itemContent { get; set; }
        public string docName { get; set; }
        public string docExtension { get; set; }
        public int? status { get; set; }
        public DateTime? createdate { get; set; }
        public DateTime? modifydate { get; set; }
        public string createBy { get; set; }
        public string modifyBy { get; set; }
        public string filName { get; set; }
        public string itemDescription { get; set; }
        public DateTime? officeOrderDate { get; set; }
        public double? OrderFactor { get; set; }

        public virtual tblPolice fkPol { get; set; }
        public virtual ICollection<tblDownLoadLog> tblDownLoadLogs { get; set; }
    }
}