// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class tblWhiteListedDevicesAndIP
    {
        public int pkLoginDetailId { get; set; }
        public string Userid { get; set; }
        public string DeviceId { get; set; }
        public string MAC { get; set; }
        public string Model { get; set; }
        public string Make { get; set; }
        public int? status { get; set; }
    }
}