// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.Models
{
    public partial class todoList
    {
        public int pkToDoListId { get; set; }
        public long? fkEmpId { get; set; }
        public string EmployeeCode { get; set; }
        public string data { get; set; }
        public DateTime? createDate { get; set; }
        public string createdBy { get; set; }
        public int? status { get; set; }

        public virtual MstEmployeeMaster fkEmp { get; set; }
    }
}