// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.FirebaseModels
{
    public partial class FirebaseNotification
    {
        public int Id { get; set; }
        public string FCM_Token { get; set; }
        public string DeviceId { get; set; }
        public int EMPId { get; set; }
        public int? CreatedBy { get; set; }
        public string CreatedSource { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public string UpdatedSource { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}