// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ModuleManagementBackend.DAL.FirebaseModels
{
    public partial class UpastithiContext : DbContext
    {
        public UpastithiContext()
        {
        }

        public UpastithiContext(DbContextOptions<UpastithiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FirebaseNotification> FirebaseNotifications { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FirebaseNotification>(entity =>
            {
                entity.Property(e => e.FCM_Token).IsRequired();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}