// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModuleManagementBackend.DAL.UpastithiModel
{
    public partial class DayWiseAttendence
    {
        public int Id { get; set; }
        public int EmployeeCode { get; set; }
        public int? ManagerEmpCode { get; set; }
        public DateTime AttendenceDate { get; set; }
        public string CheckinLongitude { get; set; }
        public string CheckinLocation { get; set; }
        public string CheckinLatitude { get; set; }
        public string CheckinPlace { get; set; }
        public string CheckInImageURL { get; set; }
        public string CheckInTime { get; set; }
        public string CheckOutLongitude { get; set; }
        public string CheckOutLatitude { get; set; }
        public string CheckOutImageURL { get; set; }
        public string CheckOutTime { get; set; }
        public string UnitName { get; set; }
        public int UnitId { get; set; }
        public bool IsSendForregularization { get; set; }
        public bool IsRegularizationCompleted { get; set; }
        public string RegularizationRemarkUser { get; set; }
        public string RegularizationRemarkManager { get; set; }
        public int? AttendenceTypeId { get; set; }
        public int RequestedAttendenceTypeId { get; set; }
        public int? ApprovedBy { get; set; }
        public int? WorkTypeId { get; set; }
        public double? TotalWorkHour { get; set; }
        public int? FinalStatusId { get; set; }
        public int? CreatedBy { get; set; }
        public string CreatedSource { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public string UpdatedSource { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public int? PunchInStatusId { get; set; }
        public int? PunchOutStatusId { get; set; }
        public string userCurrentWorkLocation { get; set; }
        public string userCurrentWorkLocationLatitude { get; set; }
        public string userCurrentWorkLocationLongitude { get; set; }
        public int ApprovedAttendenceTypeId { get; set; }
        public string ApprovedCheckInTime { get; set; }
        public string ApprovedCheckOutTime { get; set; }
        public bool? CanSendForRegularization { get; set; }
        public string RequestedCheckOutTime { get; set; }
        public string RerquestedCheckInTime { get; set; }
        public string SystemRegularizationComment { get; set; }
        public string CheckOutPlace { get; set; }
        public int? RegulariztionType { get; set; }
        public int? ApprovedWorkTypeId { get; set; }
        public int? RequestedWorkTypeId { get; set; }
        public int PunchINfrom { get; set; }
        public string CheckInImageFaceURL { get; set; }
        public string CheckOutImageURLFace { get; set; }
        public int PunchOutfrom { get; set; }
    }
}