// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace ModuleManagementBackend.DAL.UpastithiModel
{
    public partial class UpastithiDBContext : DbContext
    {
        public UpastithiDBContext()
        {
        }

        public UpastithiDBContext(DbContextOptions<UpastithiDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DayWiseAttendence> DayWiseAttendences { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DayWiseAttendence>(entity =>
            {
                entity.HasIndex(e => e.AttendenceTypeId, "IX_DayWiseAttendences_AttendenceTypeId");

                entity.HasIndex(e => e.FinalStatusId, "IX_DayWiseAttendences_FinalStatusId");

                entity.HasIndex(e => e.PunchInStatusId, "IX_DayWiseAttendences_PunchInStatusId");

                entity.HasIndex(e => e.PunchOutStatusId, "IX_DayWiseAttendences_PunchOutStatusId");

                entity.HasIndex(e => e.WorkTypeId, "IX_DayWiseAttendences_WorkTypeId");

                entity.Property(e => e.CanSendForRegularization)
                    .IsRequired()
                    .HasDefaultValueSql("(CONVERT([bit],(0)))");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}